name: lirati
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  animated_theme_switcher: ^2.0.10
  equatable: ^2.0.8
  flutter_svg: ^2.2.3
  easy_localization: ^3.0.8
  dartz: ^0.10.1
  http: ^1.6.0
  get_it: ^9.2.0
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.4
  injectable: ^2.7.1+4
  flutter_bloc: ^9.1.1
  google_fonts: ^7.0.0
  url_launcher: ^6.3.2
  tutorial_coach_mark: ^1.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.12.0
  build_runner: ^2.10.4
flutter:
  assets:
    - assets/
    - assets/svg/
    - assets/logos/
    - assets/translations/
    - assets/images/
  uses-material-design: true
