name: lirati
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  hydrated_bloc: ^10.1.1
  flutter_3d_controller: ^2.3.0
  freezed_annotation: ^3.1.0
  curved_navigation_bar: ^1.0.6
  animated_theme_switcher: ^2.0.10
  introduction_screen: ^4.0.0
  flutter_snake_navigationbar: ^0.6.1
  page_transition: ^2.2.1
  lottie: ^3.3.2
  get: ^4.7.3
  bot_toast: ^4.1.3
  shimmer: ^3.0.0
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.2.3
  easy_localization: ^3.0.8
  dartz: ^0.10.1
  http: ^1.6.0
  get_it: ^9.2.0
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  skeletonizer: ^2.1.2
  page_flip: ^0.2.5+1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.4
  injectable: ^2.7.1+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
